version: "3"
 
services:
  php:
    build:
      context: ./php
    image: "${COMPOSE_PROJECT_NAME}/php:${IMAGE_TAG}"
    hostname: "${COMPOSE_PROJECT_NAME}-php"
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=10.254.254.254
    volumes:
      - /projects/symfony/web_application:/app
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /app
  nginx:
    build:
      context: ./nginx
    image: "${COMPOSE_PROJECT_NAME}/nginx:${IMAGE_TAG}"
    hostname: "${COMPOSE_PROJECT_NAME}-nginx"
    ports:
      - "8081:80"
    expose:
      - "9000"      
    volumes:
      - /projects/symfony/web_application:/app
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php